# API configuration settings
server:
  host: "localhost"
  port: 3000

mimetypes:
  error: ["application/json"]
  json: ["application/json"]
  pdf: ["application/pdf"]
  docx: ["application/vnd.openxmlformats-officedocument.wordprocessingml.document"]

cors:
  enabled: false
  supports_credentials: false
  origins: "*"
  expose_headers:
    - "Content-Disposition"
    - "Content-Type"
    - "Content-Length"

input:
  prefer_file: true

output:
  use_temp_directory: true

logging:
  level: "INFO"
